###
get http://localhost:8080/api/physical/get/list
###
get http://localhost:8080/api/physical/get/5/applications
###
post http://localhost:8080/api/physical/create/application
Content-Type: application/json

{
    "personId": 5,
    "requestedAmount": 10000
}
###
patch http://localhost:8080/api/physical/update/application
Content-Type: application/json

{
    "id": 1,
    "status": "APPROVED"
}