get http://localhost:8080/api/physical/get/list
###
post http://localhost:8080/api/physical/create/credit
Content-Type: application/json

{
    "personId": 5,
    "amount": 10000,
    "interestRate": 0.15,
    "issuedDate": "2026-01-01",
    "type": "SHORT_TERM",
    "numberOfInstallments": 10
}
###
get http://localhost:8080/api/physical/get/5/credits