###
get http://localhost:8080/api/physical/get/list
###
get http://localhost:8080/api/physical/get/5/employment
###
post http://localhost:8080/api/physical/save/employment
Content-Type: application/json

{
    "personId": 5,
    "salary": 1000,
    "post": 1,
    "employer": "UAB ROSHEN",
    "position": "Manager",
    "startDate": "2025-01-04",
    "endDate": "",
    "workphone": "+370609"
}
###
delete http://localhost:8080/api/physical/delete/employment/1