###
get http://localhost:8080/api/physical/get/list
###
post http://localhost:8080/api/physical/save
Content-Type: application/json

{
    "citizenId": "50300000000",
    "fullname": "Justinas Bumbas",
    "telephone": "+37000000000",
    "email": "justinas@gmail.com",
    "country": "Lietuva",
    "region": "Dzukaitija",
    "city": "Vilnius",
    "zipcode": "LT-128",
    "birthday": "2020-01-01",
    "sex": "MALE"
}
###
post http://localhost:8080/api/physical/save
Content-Type: application/json

{
    "citizenId": "50300000001",
    "fullname": "Aivaras Kumbas",
    "telephone": "+37000000001",
    "email": "justinaskkk@gmail.com",
    "country": "Lietuva",
    "region": "Mazoji Lietuva",
    "city": "Klaipeda",
    "zipcode": "LT-128",
    "birthday": "2000-01-01",
    "sex": "FEMALE"
}
###
patch http://localhost:8080/api/physical/update
Content-Type: application/json

{
    "id": "1",
    "citizenId": "50400000000",
    "fullname": "Justinas Bumbas",
    "telephone": "+37000000000",
    "email": "justinasss@gmail.com",
    "country": "Lietuva",
    "region": "Dzukaitija",
    "city": "Vilnius",
    "zipcode": "LT-128",
    "birthday": "2020-01-01",
    "sex": "MALE"
}
###
get http://localhost:8080/api/physical/list
###
delete http://localhost:8080/api/physical/delete/1
###
post http://localhost:8080/api/physical/save
Content-Type: application/json

{
    "citizenId": "50300000000",
    "fullname": "Justinas Bumbas",
    "telephone": "+37000000000",
    "email": "justinas@gmail.com",
    "country": "Lietuva",
    "region": "Dzukaitija",
    "city": "Vilnius",
    "zipcode": "LT-128",
    "birthday": "2020-01-01",
    "sex": "MALE"
}
###
get http://localhost:8080/api/physical/list