###
get http://localhost:8080/api/users/get/list
###
post http://localhost:8080/api/users/create
Content-Type: application/json

{
    "email": "admin@ktu.lt",
    "password": "admin",
    "telephone": "+370606",
    "fullname": "Adminas Adminovicius",
    "citizenId": "50000001",
    "role": "ADMINISTRATOR"
}